id: P000673
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6682
  title: དེང་དུས་ཀྱི་རིག་ནུས་ལག་འཁྱེར་ཁ་པར་དང་ངོས་ལེབ་གློག་ཀླད་སྤྱོད་བརྡའི་རྒྱ་བོད་ཤན་སྦྱར།༡
  author: ''
  volumes:
    0a99f93881f248baa002457b5016e64a:
      image_group_id: I3CN6684
      title: ''
      volume_number: 1
      total_pages: 197
